services:
  java:
    image: itzg/minecraft-server:java17
    container_name: modpack
    restart: always
    environment:
      EULA: "TRUE"
      VERSION: 1.20.1
      TYPE: FORGE
      FORGE_VERSION: 47.4.0
      MEMORY: 8192  # 8GB
      SERVER_NAME: TakoyakiModpack
      LEVEL_NAME: TakoyakiModpack
      GAMEMODE: survival
      DIFFICULTY: hard
      TZ: Asia/Tokyo
      JAVA_OPTS: "-Xms8192M -Xmx8192M"  # 初期メモリと最大メモリを設定
    ports:
      - "25565:25565/tcp"
    volumes:
      - /modpack:/data

volumes:
  modpack:
